broker.id: 1
listeners: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:9093
advertised.listeners: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
listener.security.protocol.map: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
inter.broker.listener.name: PLAINTEXT_INTERNAL

num.network.threads: 3
num.io.threads: 8
socket.send.buffer.bytes: 102400
socket.receive.buffer.bytes: 102400
socket.request.max.bytes: 104857600
log.dirs: /var/lib/kafka/data
num.partitions: 1
num.recovery.threads.per.data.dir: 1
offsets.topic.replication.factor: 1
transaction.state.log.replication.factor: 1
transaction.state.log.min.isr: 1
log.retention.hours: 168
log.segment.bytes: 1073741824
log.retention.check.interval.ms: 300000
zookeeper.connect: zookeeper:2181
zookeeper.connection.timeout.ms: 6000
group.initial.rebalance.delay.ms: 0
auto.create.topics.enable: true